### ISSUE TITLE
Version 1.73 broke support for unicode characters (?)

### ISSUE THREAD

**Issue by Pkawa** [romovs/amber#145]
Characters like ó ł ć ż ą ś ź ę do not work anymore.

**Comment by romovs** [comment]
Could you provide more details? Seems to be working fine when typed into chat using Polish keyboard layout.

**Comment by sswistun-vl** [comment]
Well - when I tried nothing happened (it didn't register letters with alt).

**Comment by romovs** [comment]
Supposedly this was fixed in the default client (merged into Amber v1.73.1). Feel free to re-open if the issue still persists.
