### ISSUE TITLE
Error: Unable to access jarfile hafen.jar

### ISSUE THREAD

**Issue by BerionZ** [romovs/amber#53]
I downloaded the newest amber update but am not seeing anywhere in the files the executable jar file for hafen, so every time that I try to run it I get the error message that hafen.jar is inaccessible. Any way to fix this?

**Comment by romovs** [comment]
Does that error happen when starting the client with run.bat?

**Comment by romovs** [comment]
There was no reply from the OP in a while. Marking as resolved. Feel free to reopen if still relevant.
