### ISSUE TITLE
Clever icons

### ISSUE THREAD

**Issue by Winterwolf** [romovs/amber#58]
Please, make ability to disable clever icons on minimap. I no need this trash! :<
Also my game crashes today. Here is a log:

> 1.59.2.6a836f0b
> Linux 4.10.0-28-generic, 1.8.0_131 amd64
> NVIDIA Corporation (GeForce GTX 465/PCIe/SSE2) - 4.5.0 NVIDIA 381.22
> 
> java.lang.RuntimeException: Unknown position operation: h
> 	at haven.Widget.relpos(Widget.java:385)
> 	at haven.Widget.addchild(Widget.java:395)
> 	at haven.Widget.makechild(Widget.java:403)
> 	at haven.UI.newwidget(UI.java:159)
> 	at haven.RemoteUI.run(RemoteUI.java:66)
> 	at haven.MainFrame.run(MainFrame.java:268)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by romovs** [comment]
Icon added to the list. Will be in the upcoming update next week.
Regarding the error, was it a one time occurrence or does that happen regularly?

**Comment by Winterwolf** [comment]
It happens once. Add also Lady's Mantle please.

**Comment by romovs** [comment]
Will add.

I'll go ahead and close this, The error seems to be either just a one time network issue or a server hiccup. Feel free to reopen if it happens again.
