### ISSUE TITLE
Something wrong with mining

### ISSUE THREAD

**Issue by Winterwolf** [romovs/amber#64]
Hello. I use auto-drop option when mining, because without it I can't drink water and dig same time. After last updates this option not working if you rotate camera. Will be wonderful if you can fix this and much better if add "auto drink" function while mining (or not only mining, it can be helpful in any cases, when harvesting crop for example). Thanks.

**Comment by romovs** [comment]
Automatic drinking is not related to auto-drop option (that option only specifies whether to drop ore and rocks), server decides when to drink as long as you have flask/waterskin on your hotbar.
Previously it was done in the client, but now that loftar added option to mine whole areas I've removed that.

**Comment by Winterwolf** [comment]
Wow! I didn't know about auto drink, thanks! But here is still issue - auto drop workis only if you dig with a shift and not rotate a camera.

**Comment by romovs** [comment]
Ah yes for that I don't have a good solution at the moment, unfortunately. Will need to see if there is a way to fix that...

**Comment by romovs** [comment]
Fixed in defe56f9
Ore/stones/etc (depending on the selected options in the Settings Menu) will be dropped as long as mining cursor is active.
