### ISSUE TITLE
Mining selection box remains if you right click while selecting an area

### ISSUE THREAD

**Issue by Fevix** [romovs/amber#85]
How to reproduce:
[A] -> [M] to select Mine
Hold MB1 to start selecting an area to mine
Without releasing MB1, press MB2.

**Comment by romovs** [comment]
I can't seem to reproduce it, at least on Linux. Was there anything else done in-between those steps?

**Comment by Fevix** [comment]
Nothing else. I can grab a video next time I'm on.

**Comment by romovs** [comment]
Ah got it. Happens if M1 and M2 are released simultaneously.
