### ISSUE TITLE
"Drop all mined X" occasionally stops working

### ISSUE THREAD

**Issue by Fevix** [romovs/amber#94]
Title says all: I have the "Drop all mined stone" and "drop all mined ores" options enabled, and it works well most of the time, but sometimes it just stops working for no apparent reason.  

The only fix I've found is to cancel the mining job, drop all the items, and start mining again.

**Comment by romovs** [comment]
Did you happen to do any right clicks when mining? That option is active only when mouse cursor is in the shape of a pickaxe and right clicking would switch it to the default cursor.

**Comment by Fevix** [comment]
Ah, that's probably it. I'll reopen this if I notice it happening with the mining cursor.
